cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'
brew 'diff-so-fancy'
brew 'pkg-config'
brew 'openssl'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'direnv'
brew 'git'
brew 'go'
brew 'ffmpeg'
brew 'fzf'
brew 'jpeg'
brew 'node'
brew 'npm'
brew 'starship'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'
cask 'vlc'
